"""initial schema

Revision ID: 08f82b57aeca
Revises: 
Create Date: 2026-09-16 00:22:01.587003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f82b57aeca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('M', 'F', name='sexenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_matricule'), ['matricule'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('DIRECTION', 'ENSEIGNANT', 'SECRETARIAT', name='roleenum'), nullable=False),
    sa.Column('is_active_account', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('deliberation_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('passing_threshold_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('passing_threshold_percent >= 0 AND passing_threshold_percent <= 100', name='ck_policy_threshold_range'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliberation_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliberation_policies_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberation_policies_section_id'), ['section_id'], unique=False)

    op.create_table('evaluation_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'sequence_order', name='uq_period_year_sequence')
    )
    with op.batch_alter_table('evaluation_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_periods_academic_year_id'), ['academic_year_id'], unique=False)

    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'name', name='uq_class_year_name')
    )
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_classes_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_classes_section_id'), ['section_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('coefficient > 0', name='ck_course_coefficient_positive'),
    sa.CheckConstraint('max_score > 0', name='ck_course_max_score_positive'),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'code', name='uq_course_class_code')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_school_class_id'), ['school_class_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WITHDRAWN', 'REPEATING', name='enrollmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_enrollment_student_year')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_school_class_id'), ['school_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score >= 0', name='ck_grade_score_non_negative'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'course_id', 'period_id', name='uq_grade_enrollment_course_period')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_entered_by_id'), ['entered_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_period_id'), ['period_id'], unique=False)

    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'course_id', name='uq_assignment_teacher_course')
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('grade_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='gradeauditaction'), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_audit_logs_grade_id'), ['grade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_audit_logs_grade_id'))

    op.drop_table('grade_audit_logs')
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_course_id'))

    op.drop_table('teacher_assignments')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_period_id'))
        batch_op.drop_index(batch_op.f('ix_grades_entered_by_id'))
        batch_op.drop_index(batch_op.f('ix_grades_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_grades_course_id'))

    op.drop_table('grades')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_academic_year_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_school_class_id'))

    op.drop_table('courses')
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_classes_section_id'))
        batch_op.drop_index(batch_op.f('ix_school_classes_academic_year_id'))

    op.drop_table('school_classes')
    with op.batch_alter_table('evaluation_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_periods_academic_year_id'))

    op.drop_table('evaluation_periods')
    with op.batch_alter_table('deliberation_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliberation_policies_section_id'))
        batch_op.drop_index(batch_op.f('ix_deliberation_policies_academic_year_id'))

    op.drop_table('deliberation_policies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_matricule'))

    op.drop_table('students')
    op.drop_table('sections')
    op.drop_table('institutions')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
