"""deliberation workflow: overrides, publications, audit log

Also fixes a gap left by 9d31d5bff2f2: `DeliberationPolicy` already
inherited `TenantScopedModel` in the model layer, but that migration's
TENANT_TABLES list never actually included `deliberation_policies`, so
the column never existed in the database despite the model declaring it
— caught now because this is the first migration generated by diffing
the full model set against a real database since. Backfilled by joining
through `academic_years.ecole_id` (already correct per-tenant, unlike
the original migration's single-institution backfill, since no second
tenant existed yet when that one ran) rather than guessing a tenant.

Revision ID: bbcaf2ca88d3
Revises: 9d31d5bff2f2
Create Date: 2026-09-18 08:43:54.590602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcaf2ca88d3'
down_revision = '9d31d5bff2f2'
branch_labels = None
depends_on = None

NEW_TENANT_TABLES = ["period_publications", "deliberation_audit_logs", "deliberation_overrides"]


def upgrade():
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONSOLIDATED', 'VALIDATED', 'PUBLISHED', name='publicationstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('consolidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ecole_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecole_id', 'school_class_id', 'period_id', name='uq_publication_ecole_class_period')
    )
    with op.batch_alter_table('period_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_publications_ecole_id'), ['ecole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_publications_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_publications_school_class_id'), ['school_class_id'], unique=False)

    op.create_table('deliberation_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('MANUAL_OVERRIDE', 'CONSOLIDATE', 'VALIDATE', 'PUBLISH', name='deliberationaction'), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.String(length=1000), nullable=True),
    sa.Column('new_value', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecole_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliberation_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliberation_audit_logs_ecole_id'), ['ecole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberation_audit_logs_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberation_audit_logs_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberation_audit_logs_school_class_id'), ['school_class_id'], unique=False)

    op.create_table('deliberation_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('ADMITTED', 'DEFERRED', name='manualdecision'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ecole_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecole_id', 'enrollment_id', 'period_id', name='uq_override_ecole_enrollment_period')
    )
    with op.batch_alter_table('deliberation_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliberation_overrides_ecole_id'), ['ecole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberation_overrides_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberation_overrides_period_id'), ['period_id'], unique=False)

    with op.batch_alter_table('deliberation_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecole_id', sa.Integer(), nullable=True))

    op.execute(
        "UPDATE deliberation_policies SET ecole_id = ("
        "SELECT academic_years.ecole_id FROM academic_years "
        "WHERE academic_years.id = deliberation_policies.academic_year_id"
        ")"
    )

    with op.batch_alter_table('deliberation_policies', schema=None) as batch_op:
        batch_op.alter_column('ecole_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_deliberation_policies_ecole_id'), ['ecole_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_deliberation_policies_ecole_id_institutions', 'institutions', ['ecole_id'], ['id']
        )

    # Row Level Security — second, independent isolation layer, matching
    # 9d31d5bff2f2. Postgres only; no-op on SQLite (dev/test convenience).
    if is_postgres:
        for table_name in [*NEW_TENANT_TABLES, "deliberation_policies"]:
            op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
            op.execute(
                f"""
                CREATE POLICY tenant_isolation ON {table_name}
                USING (
                    current_setting('app.current_ecole_id', true) IS NOT NULL
                    AND current_setting('app.current_ecole_id', true) <> ''
                    AND ecole_id = current_setting('app.current_ecole_id', true)::integer
                )
                """
            )

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    if is_postgres:
        for table_name in [*NEW_TENANT_TABLES, "deliberation_policies"]:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name}")
            op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliberation_policies', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_deliberation_policies_ecole_id_institutions', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_deliberation_policies_ecole_id'))
        batch_op.drop_column('ecole_id')

    with op.batch_alter_table('deliberation_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliberation_overrides_period_id'))
        batch_op.drop_index(batch_op.f('ix_deliberation_overrides_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_deliberation_overrides_ecole_id'))

    op.drop_table('deliberation_overrides')
    with op.batch_alter_table('deliberation_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliberation_audit_logs_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_deliberation_audit_logs_period_id'))
        batch_op.drop_index(batch_op.f('ix_deliberation_audit_logs_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_deliberation_audit_logs_ecole_id'))

    op.drop_table('deliberation_audit_logs')
    with op.batch_alter_table('period_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_publications_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_period_publications_period_id'))
        batch_op.drop_index(batch_op.f('ix_period_publications_ecole_id'))

    op.drop_table('period_publications')
    # ### end Alembic commands ###
